<?php
session_start();require_once '../config/database.php';require_once 'lib.php';require_once 'dispatcher_service.php';
if(!isset($_SESSION['user_id'])){header('Location: ../login.php');exit;}
try{
    $railroad=ttDispatcherAccessRailroad($pdo,(int)$_SESSION['user_id']);
    ttDispatcherRequireAccess($railroad);
    $railroadId=(int)$railroad['id'];
    ttOperationsRequireModule($pdo,$railroadId,'dispatcher');
    if(($railroad['operations_role']??'')==='dispatcher')ttOperationsRequireModule($pdo,$railroadId,'advanced_roles');
    $modules=ttOperationsModuleStates($pdo,$railroadId);
    $stmt=$pdo->prepare("SELECT * FROM operating_sessions WHERE railroad_id=? AND status='in_progress' ORDER BY started_at DESC,id DESC");
    $stmt->execute([$railroadId]);
    $sessions=array_values(array_filter($stmt->fetchAll(PDO::FETCH_ASSOC),fn($s)=>ttDispatcherEffectiveEnabled($railroad,$s)));
    $sessionId=(int)($_GET['session_id']??($sessions[0]['id']??0));
    $session=$sessionId?ttDispatcherSession($pdo,$sessionId,$railroadId):null;
    if($session&&!ttDispatcherEffectiveEnabled($railroad,$session))throw new RuntimeException('Dispatcher is disabled for this operating session.');
    $assignments=$session?ttDispatcherAssignments($pdo,$sessionId,$railroadId):[];
    foreach($assignments as &$assignment){$assignment['crew_name']=ttOperationsCrewDisplay($assignment);$assignment['assignment_number']='Unit '.ttOperationsUnitDisplay($assignment);}
    unset($assignment);
}catch(Throwable$e){$error=$e->getMessage();$sessions=[];$session=null;$assignments=[];}
?>
<?php include '../includes/header.php';?><title>Dispatcher</title><link rel="stylesheet" href="../assets/css/operations.css"></head><body><?php include '../includes/navbar.php';?><div class="tt-operations-shell"><?php include '../assets/components/sidebar.php';?><section class="tt-ops-page">
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="tt-eyebrow">Operations</p><h1>Dispatcher</h1><p class="text-muted mb-0">Live assignment status, progress, exceptions, and crew messages.</p></div><?php if(count($sessions)>1):?><form method="get"><label class="form-label" for="dispatcherSession">Active Session</label><select class="form-select" id="dispatcherSession" name="session_id" onchange="this.form.submit()"><?php foreach($sessions as$s):?><option value="<?=(int)$s['id']?>" <?=(int)$s['id']===$sessionId?'selected':''?>><?=ttHtml($s['session_number'].' — '.($s['session_name']?:$s['operating_date']))?></option><?php endforeach;?></select></form><?php endif;?></div>
<?php if(isset($error)):?><div class="alert alert-danger"><?=ttHtml($error)?></div><?php elseif(!$session):?><div class="tt-repair-empty"><h2 class="h4">No dispatcher-enabled Active session</h2><p class="text-muted mb-0">Enable Dispatcher in Session Builder and start the session.</p></div><?php else:?><div class="alert alert-secondary py-2" id="dispatcherSync">Live overview · syncs every 15 seconds while visible</div><div class="tt-dispatcher-grid" id="dispatcherGrid"><?php foreach($assignments as$a):?><article class="card tt-dispatcher-card" data-assignment-id="<?=(int)$a['id']?>"><div class="card-header d-flex justify-content-between gap-2"><div><p class="tt-eyebrow mb-1"><?=ttHtml($a['assignment_number'])?></p><h2 class="h5 mb-0"><?=ttHtml($a['title_snapshot'])?></h2></div><span class="badge tt-dispatch-status-<?=ttHtml($a['operating_status'])?>"><?=ttHtml(ttDispatcherStatuses()[$a['operating_status']])?></span></div><div class="card-body"><dl class="tt-compact-dl"><dt>Pattern</dt><dd><?=ttHtml(ttJobTypes()[$a['operating_pattern']]??$a['operating_pattern'])?></dd><dt>Crew</dt><dd><?=ttHtml($a['crew_name']?:'Unassigned')?></dd><dt>Locomotives</dt><dd><?=ttHtml($a['locomotives']?:'None assigned')?></dd><dt>Progress</dt><dd class="tt-dispatch-progress"><?=(int)$a['completed_moves']?> / <?=(int)$a['planned_moves']?> moves</dd><dt>Exceptions</dt><dd class="tt-dispatch-exceptions"><?=(int)$a['exception_count']?></dd><dt>Last activity</dt><dd class="tt-dispatch-activity"><?=ttHtml($a['last_activity'])?></dd></dl><form class="tt-dispatch-form"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><input type="hidden" name="assignment_id" value="<?=(int)$a['id']?>"><label class="form-label">Operating Status</label><select class="form-select form-select-sm" name="operating_status" <?=$a['operating_status']==='complete'?'disabled':''?>><?php foreach(array_slice(ttDispatcherStatuses(),0,3,true)as$v=>$label):?><option value="<?=$v?>" <?=$a['operating_status']===$v?'selected':''?>><?=$label?></option><?php endforeach;?></select><label class="form-label mt-2">Dispatcher-only Note</label><textarea class="form-control form-control-sm" name="dispatcher_note" rows="2" maxlength="5000"><?=ttHtml($a['dispatcher_note'])?></textarea><?php if(!empty($modules['crew_messaging'])):?><label class="form-label mt-2">Crew Message</label><input class="form-control form-control-sm" name="crew_message" maxlength="255" value="<?=ttHtml($a['dispatcher_crew_message'])?>"><?php endif;?><button class="btn btn-sm btn-primary mt-2" <?=$a['operating_status']==='complete'?'disabled':''?>>Save Update</button></form></div></article><?php endforeach;?></div><script src="../assets/js/dispatcher.js"></script><?php endif;?></section></div><?php include '../includes/footer.php';?>
