<?php
session_start();
require_once '../config/database.php';
require_once 'lib.php';
require_once 'history_service.php';
require_once 'fast_clock_service.php';
if (!isset($_SESSION['user_id'])) { header('Location: ../login.php'); exit; }
$railroad = ttOperationsRailroad($pdo, (int)$_SESSION['user_id']);
$railroadId = (int)$railroad['id'];
$sessionId = (int)($_GET['id'] ?? 0);
$session = ttLoadOperationsHistorySession($pdo, $sessionId, $railroadId);
if (!$session) { http_response_code(404); die('Operating session history not found.'); }

$stmt=$pdo->prepare("SELECT a.*,i.industry_name base_name,sl.id switch_list_id,sl.switch_list_number,sl.revision_number,sl.status switch_list_status,sl.planned_move_count,sl.moved_count,sl.not_moved_count,sl.started_at switch_list_started_at,sl.completed_at switch_list_completed_at
  FROM operation_assignments a
  LEFT JOIN industries i ON i.id=a.operating_base_industry_id AND i.railroad_id=a.railroad_id
  LEFT JOIN operation_switch_lists sl ON sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id
    AND sl.revision_number=(SELECT MAX(sl2.revision_number) FROM operation_switch_lists sl2 WHERE sl2.assignment_id=a.id AND sl2.railroad_id=a.railroad_id AND sl2.status<>'superseded')
 WHERE a.session_id=? AND a.railroad_id=? ORDER BY a.sequence_number");
$stmt->execute([$sessionId,$railroadId]);
$assignments=$stmt->fetchAll(PDO::FETCH_ASSOC);
$assignmentIds=array_map('intval',array_column($assignments,'id'));
$byId=[];foreach($assignments as $index=>$assignment){$assignments[$index]['assignment_number']='Unit '.ttOperationsUnitDisplay($assignment);$assignments[$index]['crew_name']=ttOperationsCrewDisplay($assignment);$assignments[$index]['locomotives']=[];$assignments[$index]['moves']=[];$byId[(int)$assignment['id']]=$index;}
if($assignmentIds){
    $marks=implode(',',array_fill(0,count($assignmentIds),'?'));
    $stmt=$pdo->prepare("SELECT al.assignment_id,e.reporting_marks,e.road_number,e.road_name FROM operation_assignment_locomotives al JOIN operation_assignments a ON a.id=al.assignment_id JOIN equipment e ON e.id=al.equipment_id AND e.railroad_id=a.railroad_id WHERE a.railroad_id=? AND al.assignment_id IN ($marks) ORDER BY al.assignment_id,al.position");
    $stmt->execute(array_merge([$railroadId],$assignmentIds));foreach($stmt->fetchAll(PDO::FETCH_ASSOC) as $locomotive){$assignments[$byId[(int)$locomotive['assignment_id']]]['locomotives'][]=$locomotive;}
    $listIds=array_values(array_filter(array_map('intval',array_column($assignments,'switch_list_id'))));
    if($listIds){$listMarks=implode(',',array_fill(0,count($listIds),'?'));$stmt=$pdo->prepare("SELECT m.*,CASE WHEN m.actual_industry_id=m.destination_industry_id THEN m.destination_name_snapshot WHEN m.actual_industry_id=m.origin_industry_id THEN m.origin_name_snapshot ELSE ai.industry_name END actual_industry_name FROM operation_switch_list_moves m JOIN operation_switch_lists sl ON sl.id=m.switch_list_id AND sl.railroad_id=m.railroad_id LEFT JOIN industries ai ON ai.id=m.actual_industry_id AND ai.railroad_id=m.railroad_id WHERE m.railroad_id=? AND m.switch_list_id IN ($listMarks) ORDER BY m.switch_list_id,m.sequence_number");$stmt->execute(array_merge([$railroadId],$listIds));$listToAssignment=[];foreach($assignments as $assignment)$listToAssignment[(int)$assignment['switch_list_id']]=(int)$assignment['id'];foreach($stmt->fetchAll(PDO::FETCH_ASSOC) as $move){$assignmentId=$listToAssignment[(int)$move['switch_list_id']]??0;if($assignmentId)$assignments[$byId[$assignmentId]]['moves'][]=$move;}}
}
$allMoves=[];foreach($assignments as $assignment)$allMoves=array_merge($allMoves,$assignment['moves']);$totals=ttHistoryMoveCounts($allMoves);$crewNames=array_values(array_unique(array_filter(array_map(static fn($a)=>trim((string)$a['crew_name']),$assignments))));$locomotiveLabels=[];foreach($assignments as $assignment)foreach($assignment['locomotives'] as $locomotive)$locomotiveLabels[]=trim($locomotive['reporting_marks'].' '.$locomotive['road_number'].' '.$locomotive['road_name']);$locomotiveLabels=array_values(array_unique(array_filter($locomotiveLabels)));$closedAt=$session['status']==='completed'?$session['completed_at']:$session['cancelled_at'];
$yardHistoryStmt=$pdo->prepare("SELECT yh.*,e.reporting_marks,e.road_number,from_i.industry_name from_yard,to_i.industry_name to_yard,u.email actor_email FROM operation_yard_history yh LEFT JOIN equipment e ON e.id=yh.equipment_id AND e.railroad_id=yh.railroad_id LEFT JOIN industries from_i ON from_i.id=yh.from_yard_industry_id AND from_i.railroad_id=yh.railroad_id LEFT JOIN industries to_i ON to_i.id=yh.to_yard_industry_id AND to_i.railroad_id=yh.railroad_id LEFT JOIN users u ON u.id=yh.created_by_user_id WHERE yh.session_id=? AND yh.railroad_id=? ORDER BY yh.created_at,yh.id");$yardHistoryStmt->execute([$sessionId,$railroadId]);$yardHistory=$yardHistoryStmt->fetchAll(PDO::FETCH_ASSOC);
?>
<?php include '../includes/header.php'; ?><title><?=ttHtml($session['session_number'])?> Session History</title><link rel="stylesheet" href="../assets/css/operations.css"></head><body><?php include '../includes/navbar.php'; ?><div class="tt-operations-shell"><?php include '../assets/components/sidebar.php'; ?><section class="tt-ops-page">
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><p class="tt-eyebrow">Session History</p><h1><?=ttHtml($session['session_number'])?><?php if(trim((string)$session['session_name'])!==''):?> — <?=ttHtml($session['session_name'])?><?php endif;?></h1><p class="text-muted mb-0">Read-only operating record</p></div><div class="d-flex gap-2 align-items-center"><span class="badge tt-status-<?=ttHtml($session['status'])?>"><?=ttHtml(ttOperationsStatusLabel($session['status'],'session'))?></span><a class="btn btn-outline-secondary" href="history.php">Back to History</a></div></div>
<div class="tt-history-stats mb-4"><div class="card card-body"><small>Operating Date</small><strong><?=ttHtml(ttHistoryRecordedValue($session['operating_date']))?></strong></div><div class="card card-body"><small>Started</small><strong><?=ttHtml(ttHistoryRecordedValue($session['started_at']))?></strong></div><div class="card card-body"><small><?=($session['status']==='completed'?'Completed':'Closed')?></small><strong><?=ttHtml(ttHistoryRecordedValue($closedAt))?></strong></div><div class="card card-body"><small>Work Orders</small><strong><?=count(array_filter($assignments,static fn($a)=>!empty($a['switch_list_id'])))?></strong></div><div class="card card-body"><small>Completed Moves</small><strong><?=(int)$totals['completed']?></strong></div><div class="card card-body"><small>Exceptions</small><strong><?=(int)$totals['exceptions']?></strong></div></div>
<?php if(trim((string)$session['yardmaster_name'])!==''):?><div class="alert alert-secondary py-2"><strong>Yardmaster:</strong> <?=ttHtml($session['yardmaster_name'])?></div><?php endif;?>
<div class="card mb-4"><div class="card-body"><h2 class="h5">Session Summary</h2><dl class="row mb-0"><dt class="col-sm-3">Crew / Operators</dt><dd class="col-sm-9"><?=ttHtml($crewNames?implode(', ',$crewNames):'Not recorded')?></dd><dt class="col-sm-3">Assigned Locomotives</dt><dd class="col-sm-9"><?=ttHtml($locomotiveLabels?implode(', ',$locomotiveLabels):'Not recorded')?></dd><dt class="col-sm-3">Fast Clock</dt><dd class="col-sm-9"><?php if($session['fast_clock_enabled']):?>Enabled · <?=ttHtml(ttHistoryRecordedValue(ttFastClockFormatMinutes((int)$session['fast_clock_start_minutes'])))?> · <?=(int)$session['fast_clock_ratio']?>:1<?php else:?>Disabled<?php endif;?></dd><dt class="col-sm-3">Notes</dt><dd class="col-sm-9"><?=nl2br(ttHtml(ttHistoryRecordedValue($session['notes'])))?></dd></dl></div></div>
<?php if($yardHistory):?><section class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Yardmaster Activity</h2></div><div class="table-responsive tt-mobile-cards"><table class="table table-sm align-middle mb-0"><thead><tr><th>Time</th><th>Action</th><th>Car</th><th>Planned Track Change</th><th>Detail</th><th>By</th></tr></thead><tbody><?php foreach($yardHistory as $event):?><tr><td data-label="Time"><?=ttHtml($event['created_at'])?></td><td data-label="Action"><?=ttHtml(ucwords(str_replace('_',' ',$event['event_type'])))?></td><td data-label="Car"><?=ttHtml(trim(($event['reporting_marks']??'').' '.($event['road_number']??''))?:'—')?></td><td data-label="Planned Track Change"><?=ttHtml(($event['from_yard']?:'—').' → '.($event['to_yard']?:'—'))?></td><td data-label="Detail"><?=ttHtml($event['detail']?:'—')?></td><td data-label="By"><?=ttHtml($event['actor_email']?:'Not recorded')?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<h2 class="h4 mb-3">Work Orders / Switch Lists</h2>
<?php foreach($assignments as $assignment):?><article class="card mb-4 tt-history-work-order"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><div><p class="tt-eyebrow mb-1"><?=ttHtml($assignment['assignment_number'])?></p><h3 class="h5 mb-0"><?=ttHtml($assignment['title_snapshot'])?></h3></div><div class="text-end"><span class="badge tt-status-<?=ttHtml($assignment['status'])?>"><?=ttHtml(ttOperationsStatusLabel($assignment['status'],'assignment'))?></span><?php if($assignment['switch_list_id']):?><div class="small mt-1"><?=ttHtml($assignment['switch_list_number'])?> · Revision <?=(int)$assignment['revision_number']?> · <?=ttHtml(ttOperationsStatusLabel($assignment['switch_list_status'],'switch_list'))?></div><?php endif;?></div></div><div class="card-body"><dl class="row tt-history-work-order-meta"><dt class="col-sm-2">Crew</dt><dd class="col-sm-4"><?=ttHtml(ttHistoryRecordedValue($assignment['crew_name']))?></dd><dt class="col-sm-2">Base</dt><dd class="col-sm-4"><?=ttHtml(ttHistoryRecordedValue($assignment['base_name']))?></dd><dt class="col-sm-2">Locomotives</dt><dd class="col-sm-4"><?=ttHtml($assignment['locomotives']?implode(', ',array_map(static fn($l)=>trim($l['reporting_marks'].' '.$l['road_number']),$assignment['locomotives'])):'Not recorded')?></dd><dt class="col-sm-2">Completed</dt><dd class="col-sm-4"><?=ttHtml(ttHistoryRecordedValue($assignment['switch_list_completed_at']??$assignment['completed_at']))?></dd></dl>
<?php if($assignment['switch_list_id']):?><div class="table-responsive tt-mobile-cards"><table class="table table-sm align-middle tt-history-moves"><thead><tr><th>Car</th><th>Planned Move</th><th>Planned Destination</th><th>Actual Outcome</th><th>Actual Destination</th><th>Exception</th></tr></thead><tbody><?php foreach($assignment['moves'] as $move):?><?php if($move['action']==='LOCATION')continue;$car=trim($move['reporting_marks_snapshot'].' '.$move['road_number_snapshot']);$actualDestination=trim(ttHistoryRecordedValue($move['actual_industry_name']).($move['actual_track']?' / '.$move['actual_track']:''),' /');?><tr class="<?=trim((string)$move['exception_reason_code'])!==''?'tt-history-exception':''?>"><td data-label="Car"><strong><?=ttHtml(ttHistoryRecordedValue($car))?></strong><div class="small text-muted"><?=ttHtml(ttHistoryRecordedValue($move['equipment_type_snapshot'],'—'))?></div></td><td data-label="Planned Move"><strong><?=ttHtml($move['action'])?></strong><div class="small"><?=ttHtml(ttHistoryRecordedValue($move['instruction']))?></div></td><td data-label="Planned Destination"><?=ttHtml(ttHistoryRecordedValue(trim($move['destination_name_snapshot'].' / '.$move['destination_track'],' /')))?></td><td data-label="Actual Outcome"><?=ttHtml(ttHistoryOutcomeLabel($move))?></td><td data-label="Actual Destination"><?=ttHtml(($move['actual_outcome']??'pending')==='pending'?'Not recorded':$actualDestination)?></td><td data-label="Exception"><?php if(ttHistoryExceptionType($move)==='—'):?>—<?php else:?><strong><?=ttHtml(ttHistoryExceptionType($move))?></strong><div class="small">Reason: <?=ttHtml(ttHistoryExceptionReason($move))?></div><div class="small">Notes: <?=ttHtml(ttHistoryRecordedValue($move['exception_notes']))?></div><?php endif;?></td></tr><?php endforeach;?><?php if(!$assignment['moves']):?><tr><td colspan="6" class="text-center text-muted py-4 tt-empty-row">No persisted move records are available for this work order.</td></tr><?php endif;?></tbody></table></div><a class="btn btn-sm btn-outline-primary tt-mobile-full" href="print_order.php?id=<?=(int)$assignment['switch_list_id']?>" target="_blank" rel="noopener">Print / Reprint</a><?php else:?><div class="text-muted">No persisted work order is available for this assignment.</div><?php endif;?></div></article><?php endforeach;?>
<?php if(!$assignments):?><div class="card card-body text-center text-muted py-5">No assignment records are available for this session.</div><?php endif;?>
</section></div><?php include '../includes/footer.php'; ?>
