<?php
session_start();
require_once '../config/database.php';
require_once 'lib.php';
if (!isset($_SESSION['user_id'])) { header('Location: ../login.php'); exit; }
$railroad=ttOperationsRailroad($pdo,(int)$_SESSION['user_id']);$railroadId=(int)$railroad['id'];ttOperationsRequireRailroadOwner($pdo,$railroadId,(int)$_SESSION['user_id']);$error='';$message='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        ttOperationsRequireCsrf();
        if(($_POST['owner_confirm']??'')!=='1') throw new RuntimeException('Owner confirmation is required before load statuses are changed.');
        $updates=(array)($_POST['load_status']??[]);$selected=array_map('intval',(array)($_POST['selected']??[]));
        if(!$selected) throw new RuntimeException('Select at least one car to update.');
        $pdo->beginTransaction();$check=$pdo->prepare("SELECT id FROM equipment WHERE id=? AND railroad_id=? AND active=1 AND COALESCE(equipment_class,'')<>'Locomotive' FOR UPDATE");$update=$pdo->prepare('UPDATE equipment SET load_status=? WHERE id=? AND railroad_id=?');$count=0;
        foreach(array_unique($selected) as $equipmentId){$status=(string)($updates[$equipmentId]??'');if(!in_array($status,['Loaded','Empty'],true))throw new RuntimeException('Every selected car needs a valid Loaded or Empty status.');$check->execute([$equipmentId,$railroadId]);if(!$check->fetchColumn())throw new RuntimeException('A selected car does not belong to this railroad.');$update->execute([$status,$equipmentId,$railroadId]);$count++;}
        $pdo->commit();$message=$count.' car load '.($count===1?'status':'statuses').' updated with owner confirmation.';
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
$locationId=(int)($_GET['location_id']??0);$locationsStmt=$pdo->prepare('SELECT id,industry_name FROM industries WHERE railroad_id=? ORDER BY industry_name');$locationsStmt->execute([$railroadId]);$locations=$locationsStmt->fetchAll(PDO::FETCH_ASSOC);$params=[$railroadId];$where='e.railroad_id=? AND e.active=1 AND COALESCE(e.equipment_class,\'\')<>\'Locomotive\'';if($locationId>0){$where.=' AND e.current_industry_id=?';$params[]=$locationId;}$stmt=$pdo->prepare("SELECT e.id,e.reporting_marks,e.road_number,e.equipment_type,e.operations_service,e.load_status,e.current_track,e.photo_filename,i.industry_name FROM equipment e LEFT JOIN industries i ON i.id=e.current_industry_id AND i.railroad_id=e.railroad_id WHERE $where ORDER BY i.industry_name,e.current_track,e.reporting_marks,e.road_number");$stmt->execute($params);$cars=$stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<?php include '../includes/header.php';?><title>Review Load Status</title><link rel="stylesheet" href="../assets/css/operations.css"></head><body><?php include '../includes/navbar.php';?><div class="tt-operations-shell"><?php include '../assets/components/sidebar.php';?><section class="tt-ops-page"><p class="tt-eyebrow">Post-Session Workflow</p><h1>Review Load Status</h1><p class="text-muted">Physical switching never changes loads automatically. Review cars by location and explicitly confirm any Loaded / Empty updates.</p><?php if($message):?><div class="alert alert-success"><?=ttHtml($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=ttHtml($error)?></div><?php endif;?><form method="get" class="row g-2 mb-3"><div class="col-md-5"><label class="form-label">Location</label><select class="form-select" name="location_id" onchange="this.form.submit()"><option value="">All locations</option><?php foreach($locations as $location):?><option value="<?=(int)$location['id']?>" <?=$locationId===(int)$location['id']?'selected':''?>><?=ttHtml($location['industry_name'])?></option><?php endforeach;?></select></div></form><form method="post"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Update</th><th>Photo</th><th>Car</th><th>Location / Track</th><th>Service</th><th>Confirmed Load Status</th></tr></thead><tbody><?php foreach($cars as $car):?><tr><td><input class="form-check-input" type="checkbox" name="selected[]" value="<?=(int)$car['id']?>"></td><td><?php if($url=ttPhotoUrl($car['photo_filename'])):?><img class="tt-car-thumb" src="<?=ttHtml($url)?>" alt="<?=ttHtml(trim($car['reporting_marks'].' '.$car['road_number']))?>"><?php else:?><span class="tt-no-photo">No Photo</span><?php endif;?></td><td><strong><?=ttHtml(trim($car['reporting_marks'].' '.$car['road_number']))?></strong><br><small><?=ttHtml($car['equipment_type'])?></small></td><td><?=ttHtml(($car['industry_name']?:'Unassigned').($car['current_track']!==''?' / '.$car['current_track']:''))?></td><td><?=ttHtml($car['operations_service'])?></td><td><select class="form-select form-select-sm" name="load_status[<?=(int)$car['id']?>]"><option value="Loaded" <?=$car['load_status']==='Loaded'?'selected':''?>>Loaded</option><option value="Empty" <?=$car['load_status']==='Empty'?'selected':''?>>Empty</option></select></td></tr><?php endforeach;?></tbody></table></div></div><div class="form-check my-3"><input class="form-check-input" type="checkbox" name="owner_confirm" value="1" id="ownerConfirm"><label class="form-check-label" for="ownerConfirm">I confirm these post-session load-status changes.</label></div><button class="btn btn-primary">Update Selected Loads / Empties</button></form></section></div><?php include '../includes/footer.php';?>
