<?php
session_start();require_once '../config/database.php';require_once 'lib.php';require_once 'assignment_service.php';require_once 'fast_clock_service.php';require_once 'crew_service.php';
if(!isset($_SESSION['user_id'])){header('Location: ../login.php');exit;}
$railroad=ttOperationsRailroad($pdo,(int)$_SESSION['user_id']);$railroadId=(int)$railroad['id'];$sessionId=(int)($_GET['id']??$_POST['session_id']??0);$error='';
$stmt=$pdo->prepare('SELECT * FROM operating_sessions WHERE id=? AND railroad_id=?');
$stmt->execute([$sessionId,$railroadId]);
$session=$stmt->fetch(PDO::FETCH_ASSOC);
if(!$session){http_response_code(404);die('Operating session not found.');}
$modules=ttOperationsModuleStates($pdo,$railroadId);
if($_SERVER['REQUEST_METHOD']==='POST')try{
    ttOperationsRequireCsrf();$action=(string)($_POST['action']??'');
    if($action==='configure_fast_clock')ttOperationsRequireModule($pdo,$railroadId,'fast_clock');
    if($action==='save_dispatcher_settings')ttOperationsRequireModule($pdo,$railroadId,'dispatcher');
    if($action==='configure_fast_clock'){
        if(!ttOperatingSessionIsEditable((string)$session['status'])||!empty($session['fast_clock_started_at']))throw new RuntimeException('Fast Clock settings can only change before the clock starts.');ttOperationsRequireRailroadOwner($pdo,$railroadId,(int)$_SESSION['user_id']);$enabled=($_POST['fast_clock_enabled']??'0')==='1'?1:0;$ratio=(int)($_POST['fast_clock_ratio']??0);if(!in_array($ratio,ttFastClockRatios(),true))throw new RuntimeException('Choose a supported Fast Clock ratio.');$startMinutes=ttFastClockNormalizeStart((string)($_POST['fast_clock_start_time']??''));$stmt=$pdo->prepare('UPDATE operating_sessions SET fast_clock_enabled=?,fast_clock_running=0,fast_clock_start_minutes=?,fast_clock_ratio=?,fast_clock_base_model_seconds=?,fast_clock_base_real_at=NULL,fast_clock_last_sync_at=NOW() WHERE id=? AND railroad_id=? AND status IN(\'draft\',\'ready\') AND fast_clock_started_at IS NULL');$stmt->execute([$enabled,$startMinutes,$ratio,$startMinutes*60,$sessionId,$railroadId]);header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='save_dispatcher_settings'){
        $mode=(string)($_POST['dispatcher_mode']??'default');if(!in_array($mode,['default','enabled','disabled'],true))throw new RuntimeException('Choose a valid Dispatcher setting.');
        $pdo->beginTransaction();ttOperationsRequireRailroadOwner($pdo,$railroadId,(int)$_SESSION['user_id']);$value=$mode==='default'?null:($mode==='enabled'?1:0);$pdo->prepare('UPDATE operating_sessions SET dispatcher_enabled=? WHERE id=? AND railroad_id=?')->execute([$value,$sessionId,$railroadId]);$pdo->commit();header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='save_yardmaster_name'){
        ttOperationsRequireModule($pdo,$railroadId,'yardmaster');ttSaveSessionYardmasterName($pdo,$railroadId,$sessionId,(int)$_SESSION['user_id'],(string)($_POST['yardmaster_name']??''));header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='add_assignment'){
        if(!ttOperatingSessionIsEditable((string)$session['status']))throw new RuntimeException('This operating session is frozen and assignments cannot be created.');$pdo->beginTransaction();$stmt=$pdo->prepare('SELECT status FROM operating_sessions WHERE id=? AND railroad_id=? FOR UPDATE');$stmt->execute([$sessionId,$railroadId]);if(!ttOperatingSessionIsEditable((string)$stmt->fetchColumn()))throw new RuntimeException('This operating session became frozen and the assignment was not created.');$data=ttAssignmentNormalizeInput($pdo,$railroadId,$sessionId,$_POST);$stmt=$pdo->prepare('SELECT COALESCE(MAX(sequence_number),0)+1 FROM operation_assignments WHERE session_id=? FOR UPDATE');$stmt->execute([$sessionId]);$sequence=(int)$stmt->fetchColumn();$job=$data['job'];$number=$session['session_number'].'-'.ttAssignmentSuffix($sequence);$unitId=ttGenerateAssignmentUnitId($pdo,$railroadId,$sessionId,$job['job_name']);$status='draft';
        $stmt=$pdo->prepare('INSERT INTO operation_assignments(railroad_id,session_id,job_template_id,assignment_number,unit_identifier,sequence_number,title_snapshot,type_snapshot,description_snapshot,operating_pattern,status,operating_base_industry_id,starting_track,start_method,prepared_cut_id,requested_car_count,prepared_cut_car_count,difficulty,crew_name,engineer_name,conductor_name,brakeman_names,predecessor_assignment_id,dependency_mode,end_plan,end_industry_id,end_track,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
        $stmt->execute([$railroadId,$sessionId,$data['job_id'],$number,$unitId,$sequence,$job['job_name'],$job['job_type'],$job['description'],$data['pattern'],$status,$data['base_id'],$data['starting_track'],$data['start_method'],$data['cut_id'],$data['requested'],$data['prepared_cut_count'],$data['difficulty'],$data['crew'],$data['engineer'],$data['conductor'],$data['brakemen'],$data['predecessor'],$data['dependency'],$data['end_plan'],$data['end_id'],$data['end_track'],$data['notes']]);$assignmentId=(int)$pdo->lastInsertId();$reserved=ttReservedEquipmentIds($pdo,$railroadId,$assignmentId);ttAssignmentReplaceLocomotives($pdo,$assignmentId,$railroadId,$data['locomotive_ids'],$reserved);ttAssignmentReplaceStartingCars($pdo,$assignmentId,$railroadId,$data,$reserved);$pdo->commit();header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='start_session'){
        $pdo->beginTransaction();$stmt=$pdo->prepare('SELECT status FROM operating_sessions WHERE id=? AND railroad_id=? FOR UPDATE');$stmt->execute([$sessionId,$railroadId]);$lockedStatus=(string)$stmt->fetchColumn();if(!ttOperatingSessionIsEditable($lockedStatus))throw new RuntimeException('This operating session cannot be started from its current status.');$stmt=$pdo->prepare("SELECT a.id,a.status,a.predecessor_assignment_id,(SELECT sl.status FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id AND sl.status NOT IN('cancelled','superseded') ORDER BY sl.revision_number DESC LIMIT 1) latest_list_status FROM operation_assignments a WHERE a.session_id=? AND a.railroad_id=? FOR UPDATE");$stmt->execute([$sessionId,$railroadId]);[$canStart,$reason]=ttSessionStartReadiness($stmt->fetchAll(PDO::FETCH_ASSOC));if(!$canStart)throw new RuntimeException($reason);$stmt=$pdo->prepare("UPDATE operating_sessions SET status='in_progress',started_at=COALESCE(started_at,NOW()) WHERE id=? AND railroad_id=? AND status IN('draft','ready')");$stmt->execute([$sessionId,$railroadId]);if(!$stmt->rowCount())throw new RuntimeException('This session cannot be started from its current status.');$pdo->prepare("UPDATE operation_assignments SET status='in_progress',started_at=COALESCE(started_at,NOW()) WHERE session_id=? AND railroad_id=? AND status='ready'")->execute([$sessionId,$railroadId]);$pdo->commit();header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='complete_session'){
        $pdo->beginTransaction();$stmt=$pdo->prepare('SELECT status FROM operating_sessions WHERE id=? AND railroad_id=? FOR UPDATE');$stmt->execute([$sessionId,$railroadId]);if(!ttOperatingSessionIsActive((string)$stmt->fetchColumn()))throw new RuntimeException('Only an Active session can be completed.');$stmt=$pdo->prepare('SELECT status FROM operation_assignments WHERE session_id=? AND railroad_id=? FOR UPDATE');$stmt->execute([$sessionId,$railroadId]);[$canComplete,$reason]=ttSessionCanComplete($stmt->fetchAll(PDO::FETCH_ASSOC));if(!$canComplete)throw new RuntimeException($reason);ttFreezeFastClock($pdo,$sessionId,$railroadId);$pdo->prepare("UPDATE operating_sessions SET status='completed',completed_at=NOW() WHERE id=? AND railroad_id=? AND status='in_progress'")->execute([$sessionId,$railroadId]);$pdo->commit();header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='cancel_session'){
        $pdo->beginTransaction();$stmt=$pdo->prepare('SELECT status FROM operating_sessions WHERE id=? AND railroad_id=? FOR UPDATE');$stmt->execute([$sessionId,$railroadId]);if(!ttOperatingSessionIsActive((string)$stmt->fetchColumn()))throw new RuntimeException('Only an Active session can be cancelled.');$pdo->prepare("UPDATE operation_switch_lists SET status='cancelled',cancelled_at=NOW() WHERE session_id=? AND railroad_id=? AND status IN('draft','approved','in_progress','needs_review')")->execute([$sessionId,$railroadId]);$pdo->prepare("UPDATE prepared_cuts c JOIN operation_assignments a ON a.prepared_cut_id=c.id SET c.status='released' WHERE a.session_id=? AND a.railroad_id=? AND c.railroad_id=? AND c.status IN('assigned','in_use')")->execute([$sessionId,$railroadId,$railroadId]);$pdo->prepare("UPDATE operation_assignments SET status='aborted',cancelled_at=NOW() WHERE session_id=? AND railroad_id=? AND status IN('draft','ready','waiting','in_progress','needs_review')")->execute([$sessionId,$railroadId]);ttFreezeFastClock($pdo,$sessionId,$railroadId);$pdo->prepare("UPDATE operating_sessions SET status='cancelled',cancelled_at=NOW() WHERE id=? AND railroad_id=? AND status='in_progress'")->execute([$sessionId,$railroadId]);$pdo->commit();header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='delete_draft_session'){
        $pdo->beginTransaction();$stmt=$pdo->prepare('SELECT status FROM operating_sessions WHERE id=? AND railroad_id=? FOR UPDATE');$stmt->execute([$sessionId,$railroadId]);if(!ttOperatingSessionIsEditable((string)$stmt->fetchColumn()))throw new RuntimeException('A session cannot be deleted after it starts.');$pdo->prepare("UPDATE prepared_cuts c JOIN operation_assignments a ON a.prepared_cut_id=c.id SET c.status='ready' WHERE a.session_id=? AND a.railroad_id=? AND c.railroad_id=? AND c.status='assigned'")->execute([$sessionId,$railroadId,$railroadId]);$pdo->prepare('DELETE m FROM operation_switch_list_moves m JOIN operation_switch_lists sl ON sl.id=m.switch_list_id WHERE sl.session_id=? AND sl.railroad_id=?')->execute([$sessionId,$railroadId]);$pdo->prepare('DELETE FROM operation_switch_lists WHERE session_id=? AND railroad_id=?')->execute([$sessionId,$railroadId]);$pdo->prepare('DELETE al FROM operation_assignment_locomotives al JOIN operation_assignments a ON a.id=al.assignment_id WHERE a.session_id=? AND a.railroad_id=?')->execute([$sessionId,$railroadId]);$pdo->prepare('DELETE ac FROM operation_assignment_starting_cars ac JOIN operation_assignments a ON a.id=ac.assignment_id WHERE a.session_id=? AND a.railroad_id=?')->execute([$sessionId,$railroadId]);$pdo->prepare('UPDATE operation_assignments SET predecessor_assignment_id=NULL WHERE session_id=? AND railroad_id=?')->execute([$sessionId,$railroadId]);$pdo->prepare('DELETE FROM operation_assignments WHERE session_id=? AND railroad_id=?')->execute([$sessionId,$railroadId]);$pdo->prepare("DELETE FROM operating_sessions WHERE id=? AND railroad_id=? AND status IN('draft','ready')")->execute([$sessionId,$railroadId]);$pdo->commit();header('Location: sessions.php');exit;
    }
    throw new RuntimeException('Invalid Session Builder action.');
}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
$jobsStmt=$pdo->prepare("SELECT j.id,j.job_name,j.job_type,j.description,COALESCE(jop.work_scope,'entire_railroad') work_scope FROM jobs j LEFT JOIN job_operation_profiles jop ON jop.job_id=j.id AND jop.railroad_id=j.railroad_id WHERE j.railroad_id=? AND j.active=1 ORDER BY j.job_name");$jobsStmt->execute([$railroadId]);$jobs=$jobsStmt->fetchAll(PDO::FETCH_ASSOC);
$industriesStmt=$pdo->prepare('SELECT id,industry_name FROM industries WHERE railroad_id=? AND active=1 ORDER BY industry_name');$industriesStmt->execute([$railroadId]);$industries=$industriesStmt->fetchAll(PDO::FETCH_ASSOC);
$locosStmt=$pdo->prepare("SELECT id,reporting_marks,road_number,road_name,current_track FROM equipment WHERE railroad_id=? AND active=1 AND equipment_class='Locomotive' ORDER BY reporting_marks,road_number");$locosStmt->execute([$railroadId]);$locomotives=$locosStmt->fetchAll(PDO::FETCH_ASSOC);
$carsStmt=$pdo->prepare("SELECT e.id,e.reporting_marks,e.road_number,e.equipment_type,e.current_industry_id,e.current_track,i.industry_name FROM equipment e JOIN industries i ON i.id=e.current_industry_id AND i.railroad_id=e.railroad_id WHERE e.railroad_id=? AND e.active=1 AND COALESCE(e.equipment_class,'')<>'Locomotive' AND NOT EXISTS(SELECT 1 FROM operation_assignment_starting_cars ac JOIN operation_assignments a ON a.id=ac.assignment_id WHERE ac.equipment_id=e.id AND a.railroad_id=e.railroad_id AND a.status IN('draft','ready','waiting','in_progress','needs_review')) ORDER BY e.reporting_marks,e.road_number");$carsStmt->execute([$railroadId]);$startingCars=$carsStmt->fetchAll(PDO::FETCH_ASSOC);
$cutsStmt=$pdo->prepare("SELECT c.*,COUNT(pc.equipment_id) car_count,i.industry_name FROM prepared_cuts c JOIN industries i ON i.id=c.current_industry_id AND i.railroad_id=c.railroad_id LEFT JOIN prepared_cut_cars pc ON pc.prepared_cut_id=c.id WHERE c.railroad_id=? AND c.status='ready' AND NOT EXISTS(SELECT 1 FROM prepared_cut_cars pc2 JOIN operation_assignment_starting_cars ac2 ON ac2.equipment_id=pc2.equipment_id JOIN operation_assignments a2 ON a2.id=ac2.assignment_id WHERE pc2.prepared_cut_id=c.id AND a2.railroad_id=c.railroad_id AND a2.status IN('draft','ready','waiting','in_progress','needs_review')) GROUP BY c.id ORDER BY c.cut_number");$cutsStmt->execute([$railroadId]);$cuts=$cutsStmt->fetchAll(PDO::FETCH_ASSOC);
$assignStmt=$pdo->prepare("SELECT a.*,? session_status,i.industry_name base_name,(SELECT COUNT(*) FROM operation_assignment_locomotives al WHERE al.assignment_id=a.id) locomotive_count,(SELECT COUNT(*) FROM operation_assignment_starting_cars ac WHERE ac.assignment_id=a.id) starting_car_count,(SELECT sl.id FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id AND sl.status NOT IN('cancelled','superseded') ORDER BY sl.revision_number DESC LIMIT 1) switch_list_id,(SELECT sl.status FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id AND sl.status NOT IN('cancelled','superseded') ORDER BY sl.revision_number DESC LIMIT 1) switch_list_status,(SELECT sl.status FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id AND sl.status NOT IN('cancelled','superseded') ORDER BY sl.revision_number DESC LIMIT 1) latest_list_status,(SELECT sl.planned_move_count FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id AND sl.status NOT IN('cancelled','superseded') ORDER BY sl.revision_number DESC LIMIT 1) planned_move_count,(SELECT COUNT(*) FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id AND sl.status IN('in_progress','completed','needs_review')) frozen_list_count FROM operation_assignments a LEFT JOIN industries i ON i.id=a.operating_base_industry_id AND i.railroad_id=a.railroad_id WHERE a.session_id=? AND a.railroad_id=? ORDER BY a.sequence_number");$assignStmt->execute([(string)$session['status'],$sessionId,$railroadId]);$assignments=$assignStmt->fetchAll(PDO::FETCH_ASSOC);if(ttOperatingSessionIsHistory((string)$session['status'])){$historyStmt=$pdo->prepare('SELECT id,status,planned_move_count FROM operation_switch_lists WHERE assignment_id=? AND railroad_id=? ORDER BY revision_number DESC LIMIT 1');foreach($assignments as&$assignment){if(!$assignment['switch_list_id']){$historyStmt->execute([(int)$assignment['id'],$railroadId]);if($history=$historyStmt->fetch(PDO::FETCH_ASSOC)){$assignment['switch_list_id']=$history['id'];$assignment['switch_list_status']=$history['status'];$assignment['planned_move_count']=$history['planned_move_count'];}}}unset($assignment);}[$canStart,$startReason]=ttSessionStartReadiness($assignments);if(!ttOperatingSessionIsEditable((string)$session['status'])){$canStart=false;$startReason='This operating session cannot be started from its current status.';}foreach($assignments as&$assignment)$assignment['assignment_number']='Unit '.ttOperationsUnitDisplay($assignment);unset($assignment);$patterns=ttJobTypes();
?>
<?php include '../includes/header.php';?><title><?=ttHtml($session['session_number'])?> Session Builder</title><link rel="stylesheet" href="../assets/css/operations.css"></head><body><?php include '../includes/navbar.php';?><div class="tt-operations-shell"><?php include '../assets/components/sidebar.php';?><section class="tt-ops-page"><?php $fastClockSessionId=$sessionId;include 'fast_clock_widget.php';?>
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><p class="tt-eyebrow">Operating Session</p><h1><?=ttHtml($session['session_number'])?><?=$session['session_name']?' — '.ttHtml($session['session_name']):''?></h1><p class="text-muted"><?=ttHtml($session['operating_date'])?> · <span class="badge tt-status-<?=ttHtml($session['status'])?>"><?=ttHtml(ttOperationsStatusLabel($session['status'],'session'))?></span></p></div><div class="d-flex flex-wrap gap-2"><?php if(ttOperatingSessionIsEditable((string)$session['status'])):?><form method="post"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><button class="btn btn-success" name="action" value="start_session" <?=$canStart?'':'disabled'?>>Start Session</button><?php if(!$canStart):?><small class="d-block text-muted mt-2" style="max-width:28rem"><?=ttHtml($startReason)?></small><?php endif;?></form><form method="post" onsubmit="return confirm('Delete this Draft session and all of its assignments and switch-list revisions?')"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><button class="btn btn-outline-danger" name="action" value="delete_draft_session">Delete Draft Session</button></form><?php elseif(ttOperatingSessionIsActive((string)$session['status'])):?><form method="post" onsubmit="return confirm('Complete this operating session?')"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><button class="btn btn-success" name="action" value="complete_session">Complete Session</button></form><form method="post" onsubmit="return confirm('Cancel this Active session? Unfinished assignments will be aborted and car locations will not be changed.')"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><button class="btn btn-outline-danger" name="action" value="cancel_session">Cancel Session</button></form><?php endif;?></div></div>
<p><a class="btn btn-outline-primary" href="invitations.php?id=<?=$sessionId?>">Invite Crew by Email or QR Code</a></p>
<?php if($error):?><div class="alert alert-danger"><?=ttHtml($error)?></div><?php endif;?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-2 mb-3"><div><p class="tt-eyebrow mb-1">Session work</p><h2 class="h4 mb-0">Assignments</h2></div><?php if(ttOperatingSessionIsEditable((string)$session['status'])):?><small class="text-muted">Add or edit an assignment to change its crew.</small><?php endif;?></div>
<div class="tt-assignment-grid mb-4"><?php foreach($assignments as$a):?><?php $retainedStatuses=(int)$a['frozen_list_count']>0?['in_progress']:array_filter([(string)$a['switch_list_status']]);$legacy=$a['start_method']==='inherit'||!in_array($a['end_plan'],ttAssignmentEndPlans(),true);$editable=!$legacy&&ttAssignmentIsEditable($a,$retainedStatuses);$generatable=ttAssignmentCanGenerate($a,$retainedStatuses);?><article class="tt-assignment-card"><div class="d-flex justify-content-between"><div><p class="tt-eyebrow mb-1"><?=ttHtml($a['assignment_number'])?></p><h3><?=ttHtml($a['title_snapshot'])?></h3></div><span class="badge tt-status-<?=ttHtml($a['status'])?>"><?=ttHtml(ttOperationsStatusLabel($a['status'],'assignment'))?></span></div><dl class="tt-compact-dl"><dt>Pattern</dt><dd><?=ttHtml($patterns[$a['operating_pattern']]??$a['operating_pattern'])?></dd><dt>Crew</dt><dd><?=ttHtml(ttOperationsCrewDisplay($a))?></dd><dt>Base</dt><dd><?=ttHtml($a['base_name']?:'Not selected')?></dd><dt>Locomotives</dt><dd><?=(int)$a['locomotive_count']?></dd><dt>Starting cars</dt><dd><?=(int)$a['starting_car_count']?></dd><dt>Planned moves</dt><dd><?=(int)($a['planned_move_count']??0)?></dd></dl><?php if($legacy):?><div class="alert alert-secondary py-2">Legacy inheritance or end-plan settings are preserved read-only and deferred to a future focused update.</div><?php endif;?><div class="d-flex flex-wrap gap-2">
<?php if($editable):?><a class="btn btn-sm btn-outline-secondary" href="assignment_edit.php?id=<?=(int)$a['id']?>">Edit Assignment</a><?php endif;?>
<?php if(!$a['switch_list_id']&&$generatable):?><form class="d-inline" method="post" action="generate.php"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="assignment_id" value="<?=(int)$a['id']?>"><button class="btn btn-sm btn-primary">Generate Switch List</button></form><?php elseif($a['switch_list_status']==='draft'):?><a class="btn btn-sm btn-primary" href="work_order.php?id=<?=(int)$a['switch_list_id']?>">Review Switch List</a><?php if($generatable):?><form class="d-inline" method="post" action="generate.php"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="assignment_id" value="<?=(int)$a['id']?>"><button class="btn btn-sm btn-outline-primary">Regenerate Switch List</button></form><?php endif;?><?php elseif($a['switch_list_id']):?><a class="btn btn-sm btn-primary" href="work_order.php?id=<?=(int)$a['switch_list_id']?>"><?=ttOperatingSessionIsActive((string)$session['status'])?'Open / Run Switch List':'View Switch List'?></a><?php if($generatable):?><form class="d-inline" method="post" action="generate.php"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="assignment_id" value="<?=(int)$a['id']?>"><button class="btn btn-sm btn-outline-primary">Regenerate Switch List</button></form><?php endif;?><?php endif;?>
<?php if($editable):?><form method="post" action="assignment_delete.php" onsubmit="return confirm('Remove <?=ttHtml($a['assignment_number'])?>? This physically deletes only safe Draft-session data.')"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="assignment_id" value="<?=(int)$a['id']?>"><button class="btn btn-sm btn-outline-danger">Remove Assignment</button></form><?php endif;?></div></article><?php endforeach;?><?php if(!$assignments):?><div class="card card-body text-center text-muted py-4">No assignments have been created for this session.</div><?php endif;?></div>
<?php if(!empty($modules['fast_clock'])&&ttOperatingSessionIsEditable((string)$session['status'])):?><div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Fast Clock</h2></div><div class="card-body"><form method="post" class="row g-3 align-items-end"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><input type="hidden" name="action" value="configure_fast_clock"><div class="col-12"><input type="hidden" name="fast_clock_enabled" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="fast_clock_enabled" value="1" id="fastClockEnabled" <?=$session['fast_clock_enabled']?'checked':''?>><label class="form-check-label" for="fastClockEnabled">Enable Fast Clock for this session</label></div></div><div class="col-sm-5 col-md-3"><label class="form-label">Configured Start Time</label><input class="form-control" type="time" name="fast_clock_start_time" value="<?=ttHtml(ttFastClockFormatMinutes((int)$session['fast_clock_start_minutes']))?>" required></div><div class="col-sm-4 col-md-3"><label class="form-label">Ratio</label><select class="form-select" name="fast_clock_ratio"><?php foreach(ttFastClockRatios() as$ratio):?><option value="<?=$ratio?>" <?=(int)$session['fast_clock_ratio']===$ratio?'selected':''?>><?=$ratio?>:1</option><?php endforeach;?></select></div><div class="col-sm-3"><button class="btn btn-outline-primary">Save Clock Settings</button></div><div class="col-12"><small class="text-muted">Settings lock after the clock first starts. Starting the operating session does not automatically start the Fast Clock.</small></div></form></div></div><?php elseif(!empty($modules['fast_clock'])&&!$session['fast_clock_enabled']):?><div class="alert alert-secondary">Fast Clock is disabled for this session.</div><?php endif;?>
<?php if(!empty($modules['dispatcher'])):?><div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Dispatcher</h2></div><div class="card-body"><form method="post" class="row g-3 align-items-end"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><input type="hidden" name="action" value="save_dispatcher_settings"><div class="col-md-5"><label class="form-label">This Session</label><select class="form-select" name="dispatcher_mode"><option value="default" <?=$session['dispatcher_enabled']===null?'selected':''?>>Use railroad default</option><option value="enabled" <?=$session['dispatcher_enabled']!==null&&(int)$session['dispatcher_enabled']===1?'selected':''?>>Enabled</option><option value="disabled" <?=$session['dispatcher_enabled']!==null&&(int)$session['dispatcher_enabled']===0?'selected':''?>>Disabled</option></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Save</button></div></form><p class="form-text mb-0 mt-2">Only owners and railroad-scoped dispatcher-role users can open the live overview. Settings may be changed without affecting switch lists or car movement.</p></div></div><?php endif;?>
<?php if(!empty($modules['yardmaster'])&&!ttOperatingSessionIsHistory((string)$session['status'])):?><div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Yardmaster</h2></div><div class="card-body"><form method="post" class="row g-3 align-items-end"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><input type="hidden" name="action" value="save_yardmaster_name"><div class="col-md-8"><label class="form-label" for="yardmasterName">Name</label><input class="form-control" id="yardmasterName" name="yardmaster_name" value="<?=ttHtml($session['yardmaster_name'])?>" maxlength="120" placeholder="Optional name"><div class="form-text">This identifies the session Yardmaster; it does not grant login access.</div></div><div class="col-md-4"><button class="btn btn-outline-primary tt-mobile-full">Save Yardmaster</button></div></form></div></div><?php endif;?>
<?php if(ttOperatingSessionIsEditable((string)$session['status'])):?><div class="card"><div class="card-header"><h2 class="h4 mb-0">Create Assignment</h2></div><div class="card-body"><form method="post" class="row g-3 tt-assignment-form"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><input type="hidden" name="action" value="add_assignment">
<div class="col-md-6"><label class="form-label">Job Title</label><select class="form-select" name="job_template_id" required><option value="">Choose…</option><?php foreach($jobs as$job):?><?php $jobPattern=$patterns[$job['job_type']]??$job['job_type'];$jobScope=$job['work_scope']==='selected_route'?'Selected Operating Areas':'Entire Railroad';?><option value="<?=(int)$job['id']?>" data-pattern="<?=ttHtml($job['job_type'])?>" data-pattern-label="<?=ttHtml($jobPattern)?>" data-scope-label="<?=ttHtml($jobScope)?>" data-description="<?=ttHtml($job['description'])?>"><?=ttHtml($job['job_name'].' — '.$jobPattern.' · '.$jobScope)?></option><?php endforeach;?></select><div class="tt-job-summary form-text mt-2" aria-live="polite" hidden><strong data-job-pattern></strong><span aria-hidden="true"> · </span><span data-job-scope></span><span class="d-block" data-job-description></span></div></div>
<div class="col-md-6"><label class="form-label">Start Method</label><select class="form-select" name="start_method"><option value="locomotives_only">Locomotives only</option><option value="prepared_cut">Travel light to pick up a prepared cut</option><option value="coupled_selected">Already coupled to selected cars</option><option value="manual">Select starting cars manually</option><option value="auto_build">Auto-build</option></select></div>
<div class="col-md-6 tt-field-base"><label class="form-label">Operating Base</label><select class="form-select" name="operating_base_industry_id"><option value="">Choose…</option><?php foreach($industries as$i):?><option value="<?=(int)$i['id']?>"><?=ttHtml($i['industry_name'])?></option><?php endforeach;?></select></div><div class="col-md-6 tt-field-track"><label class="form-label">Starting Track</label><input class="form-control" name="starting_track" maxlength="120"></div>
<div class="col-12 tt-field-cut" hidden><label class="form-label">Prepared Cut</label><select class="form-select" name="prepared_cut_id"><option value="">Choose…</option><?php foreach($cuts as$c):?><option value="<?=(int)$c['id']?>" data-summary="<?=ttHtml($c['industry_name'].($c['current_track']!==''?' / '.$c['current_track']:'').' · '.$c['car_count'].' cars')?>"><?=ttHtml($c['cut_number'].' — '.$c['name'])?></option><?php endforeach;?></select><div class="form-text tt-cut-summary"></div></div>
<div class="col-12 tt-field-locos"><label class="form-label">Locomotives</label><div class="tt-check-grid"><?php foreach($locomotives as$l):?><label><input type="checkbox" name="locomotive_ids[]" value="<?=(int)$l['id']?>"> <?=ttHtml(trim($l['reporting_marks'].' '.$l['road_number'].' '.$l['road_name']))?></label><?php endforeach;?></div></div>
<div class="col-12 tt-field-cars" hidden><label class="form-label">Starting Cars</label><div class="tt-check-grid"><?php foreach($startingCars as$c):?><label data-location-id="<?=(int)$c['current_industry_id']?>"><input type="checkbox" name="starting_car_ids[]" value="<?=(int)$c['id']?>"> <?=ttHtml(trim($c['reporting_marks'].' '.$c['road_number'].' '.$c['equipment_type'].' — '.$c['industry_name'].($c['current_track']!==''?' / '.$c['current_track']:'')))?></label><?php endforeach;?></div><div class="form-text">Cars are limited to the selected Operating Base; coupled cars must also match Starting Track.</div></div>
<div class="col-md-4"><label class="form-label">Engineer</label><input class="form-control" name="engineer_name" maxlength="120" placeholder="Optional"></div><div class="col-md-4"><label class="form-label">Conductor / Yard Foreman</label><input class="form-control" name="conductor_name" maxlength="120" placeholder="Optional"></div><div class="col-md-4"><label class="form-label">Brakeman / Switchman</label><input class="form-control" name="brakeman_names" maxlength="255" placeholder="Optional; comma-separated"></div>
<div class="col-12"><details class="tt-advanced"><summary class="btn btn-sm btn-outline-secondary">Advanced Options</summary><div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label">Operating Pattern Override</label><select class="form-select" name="operating_pattern"><option value="">Use Job Title default</option><?php foreach($patterns as$v=>$label):?><option value="<?=ttHtml($v)?>"><?=ttHtml($label)?></option><?php endforeach;?></select></div><div class="col-md-3 tt-field-prepared-switch-limit" hidden><label class="form-label">Prepared Cut Cars to Switch</label><input class="form-control" type="number" name="prepared_cut_car_count" min="0" max="100" value="10"><div class="form-text">Only this many prepared-cut cars may receive Spot moves.</div></div><div class="col-md-3"><label class="form-label"><span class="tt-requested-label">Cars To Switch (maximum)</span></label><input class="form-control" type="number" name="requested_car_count" min="0" max="100" value="10"><div class="form-text tt-prepared-pickup-help" hidden>This limit applies only to additional pickups at configured Operating Areas.</div></div><div class="col-md-3"><label class="form-label">Difficulty</label><select class="form-select" name="difficulty"><option>easy</option><option selected>medium</option><option>hard</option></select></div><div class="col-md-6"><label class="form-label">End Plan</label><select class="form-select" name="end_plan"><option value="return_origin">Return to origin and tie down</option><option value="terminate_elsewhere">Terminate at another location</option></select></div><div class="col-md-3 tt-field-end"><label class="form-label">End Location <span class="text-muted">(required for Terminate elsewhere)</span></label><select class="form-select" name="end_industry_id"><option value="">As planned</option><?php foreach($industries as$i):?><option value="<?=(int)$i['id']?>"><?=ttHtml($i['industry_name'])?></option><?php endforeach;?></select></div><div class="col-md-3 tt-field-end"><label class="form-label">End Track</label><input class="form-control" name="end_track" maxlength="120"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div></div></details></div><div><button class="btn btn-primary">Add Assignment</button></div></form></div></div>
<?php else:?><?php if(ttOperatingSessionIsHistory((string)$session['status'])):?><div class="alert alert-secondary">This session is read-only history.</div><?php else:?><div class="alert alert-info">This session is Active. Run switch lists or explicitly complete or cancel the session.</div><?php endif;?><?php endif;?></section></div><script src="../assets/js/assignment-form.js"></script><?php include '../includes/footer.php';?>
