<?php
session_start();
require_once '../config/database.php';
require_once 'lib.php';
require_once 'completion.php';
require_once 'assignment_service.php';
if(!isset($_SESSION['user_id'])){header('Location: ../login.php');exit;}
$railroad=ttOperationsRailroad($pdo,(int)$_SESSION['user_id']);$railroadId=(int)$railroad['id'];$id=(int)($_GET['id']??$_POST['id']??0);$error='';$message='';$modules=ttOperationsModuleStates($pdo,$railroadId);$repairQueueEnabled=!empty($modules['repair_queue']);$exceptionReasons=['track_blocked'=>'Track blocked','car_inaccessible'=>'Car inaccessible','no_capacity'=>'No capacity / track full','wrong_car'=>'Wrong car','customer_not_ready'=>'Customer not ready','locomotive_issue'=>'Locomotive issue','crew_issue'=>'Crew issue','order_changed'=>'Order changed','other'=>'Other'];if($repairQueueEnabled)$exceptionReasons=['track_blocked'=>'Track blocked','car_inaccessible'=>'Car inaccessible','no_capacity'=>'No capacity / track full','bad_order'=>'Bad order']+$exceptionReasons;
function ttLoadWorkOrder(PDO $pdo,int $id,int $railroadId):array{$stmt=$pdo->prepare('SELECT sl.*,a.assignment_number,a.unit_identifier,a.title_snapshot,a.operating_pattern,a.status assignment_status,a.operating_base_industry_id,a.starting_track,a.start_method,a.crew_name,a.engineer_name,a.conductor_name,a.brakeman_names,a.dispatcher_crew_message,a.end_plan,a.end_industry_id,a.end_track,a.predecessor_assignment_id,s.status session_status,s.session_number,s.session_name,s.operating_date,i.industry_name base_name FROM operation_switch_lists sl JOIN operation_assignments a ON a.id=sl.assignment_id AND a.railroad_id=sl.railroad_id JOIN operating_sessions s ON s.id=sl.session_id AND s.railroad_id=sl.railroad_id LEFT JOIN industries i ON i.id=a.operating_base_industry_id WHERE sl.id=? AND sl.railroad_id=?');$stmt->execute([$id,$railroadId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row){http_response_code(404);die('Work order not found.');}$row['crew_name']=ttOperationsCrewDisplay($row);$row['base_name']='Unit '.ttOperationsUnitDisplay($row).' · '.($row['base_name']?:'No base');return$row;}
$list=ttLoadWorkOrder($pdo,$id,$railroadId);
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{ttOperationsRequireCsrf();$action=(string)($_POST['action']??'');
  if($action==='approve'){
   $pdo->beginTransaction();$sessionLock=$pdo->prepare('SELECT status FROM operating_sessions WHERE id=? AND railroad_id=? FOR UPDATE');$sessionLock->execute([(int)$list['session_id'],$railroadId]);$sessionStatus=$sessionLock->fetchColumn();$assignmentLock=$pdo->prepare('SELECT * FROM operation_assignments WHERE id=? AND railroad_id=? FOR UPDATE');$assignmentLock->execute([(int)$list['assignment_id'],$railroadId]);$lockedAssignment=$assignmentLock->fetch(PDO::FETCH_ASSOC);if(!$lockedAssignment)throw new RuntimeException('Assignment not found.');$lockedAssignment['session_status']=(string)$sessionStatus;$summary=ttSwitchListRevisionSummary($pdo,(int)$list['assignment_id'],$railroadId,true);$lockedList=null;foreach($summary['rows']as$row)if((int)$row['id']===$id){$lockedList=$row;break;}if(!$lockedList||!ttSwitchListIsApprovable($lockedList,$lockedAssignment,$summary)){http_response_code(409);throw new RuntimeException('This switch-list draft is stale, superseded, or no longer safe to approve. Open the latest current revision.');}
   $stmt=$pdo->prepare("UPDATE operation_switch_lists SET status='approved',approved_at=NOW(),approved_by_user_id=? WHERE id=? AND railroad_id=? AND status='draft'");$stmt->execute([(int)$_SESSION['user_id'],$id,$railroadId]);if($stmt->rowCount()!==1){http_response_code(409);throw new RuntimeException('This switch-list draft changed before approval.');}$pdo->prepare("UPDATE operation_assignments SET status=IF(predecessor_assignment_id IS NULL,'ready','waiting'),approved_at=NOW() WHERE id=? AND railroad_id=?")->execute([(int)$list['assignment_id'],$railroadId]);if($list['start_method']==='prepared_cut')$pdo->prepare("UPDATE prepared_cuts SET status='assigned' WHERE id=(SELECT prepared_cut_id FROM operation_assignments WHERE id=?) AND status='ready'")->execute([(int)$list['assignment_id']]);$pdo->commit();$message='Revision approved and frozen.';
  }
  elseif($action==='abort'){$pdo->beginTransaction();$note=substr(trim((string)($_POST['abort_note']??'')),0,5000);$lock=$pdo->prepare('SELECT a.status assignment_status,s.status session_status FROM operation_assignments a JOIN operating_sessions s ON s.id=a.session_id AND s.railroad_id=a.railroad_id WHERE a.id=? AND a.railroad_id=? FOR UPDATE');$lock->execute([(int)$list['assignment_id'],$railroadId]);$state=$lock->fetch(PDO::FETCH_ASSOC);if(!$state||$state['session_status']!=='in_progress'||!in_array($state['assignment_status'],['ready','waiting','in_progress','needs_review'],true))throw new RuntimeException('An assignment can only be aborted after its operating session starts and before the assignment is completed.');$pdo->prepare("UPDATE operation_switch_lists SET status='cancelled',cancelled_at=NOW(),notes=CONCAT_WS(' ',NULLIF(TRIM(COALESCE(notes,'')),''),NULLIF(?,'')) WHERE id=? AND railroad_id=? AND status IN('draft','approved','in_progress','needs_review')")->execute([$note,$id,$railroadId]);$pdo->prepare("UPDATE operation_assignments SET status='aborted',cancelled_at=NOW() WHERE id=? AND railroad_id=?")->execute([(int)$list['assignment_id'],$railroadId]);$pdo->prepare("UPDATE prepared_cuts SET status='released' WHERE id=(SELECT prepared_cut_id FROM operation_assignments WHERE id=?) AND status IN('assigned','in_use')")->execute([(int)$list['assignment_id']]);$pdo->commit();$message='Assignment aborted. No equipment locations changed.';}
  elseif($action==='complete'){if(!$repairQueueEnabled&&in_array('bad_order',(array)($_POST['reason']??[]),true))throw new RuntimeException('Repair Queue is disabled for this railroad.');$completion=ttCompleteWorkOrderLoadNeutral($pdo,$list,$railroadId,$_POST,(int)$_SESSION['user_id']);$message='Work order completed: '.$completion['moved_as_planned'].' moved as planned'.($completion['moved_different']?', '.$completion['moved_different'].' moved to a different location':'').', '.$completion['not_moved'].' not moved. Load status remains unchanged until owner review.';}
  else throw new RuntimeException('Invalid work-order action.');$list=ttLoadWorkOrder($pdo,$id,$railroadId);
 }catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
$stmt=$pdo->prepare('SELECT m.*,oi.industry_name actual_industry_name FROM operation_switch_list_moves m LEFT JOIN industries oi ON oi.id=m.actual_industry_id WHERE m.switch_list_id=? AND m.railroad_id=? ORDER BY m.sequence_number');$stmt->execute([$id,$railroadId]);$moves=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare('SELECT e.reporting_marks,e.road_number,e.photo_filename FROM operation_assignment_locomotives al JOIN equipment e ON e.id=al.equipment_id AND e.railroad_id=? WHERE al.assignment_id=? ORDER BY al.position');$stmt->execute([$railroadId,(int)$list['assignment_id']]);$locomotives=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare('SELECT id,industry_name FROM industries WHERE railroad_id=? AND active=1 ORDER BY industry_name');$stmt->execute([$railroadId]);$industries=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare('SELECT id,revision_number,status FROM operation_switch_lists WHERE assignment_id=? AND railroad_id=? ORDER BY revision_number DESC');$stmt->execute([(int)$list['assignment_id'],$railroadId]);$revisions=$stmt->fetchAll(PDO::FETCH_ASSOC);
$revisionSummary=ttSwitchListRevisionSummary($pdo,(int)$list['assignment_id'],$railroadId);$approvalAssignment=['status'=>$list['assignment_status'],'session_status'=>$list['session_status'],'start_method'=>$list['start_method'],'end_plan'=>$list['end_plan']];$canApprove=ttSwitchListIsApprovable($list,$approvalAssignment,$revisionSummary);$canRegenerate=$canApprove;$closeout=$list['session_status']==='in_progress'&&in_array($list['assignment_status'],['ready','in_progress','needs_review'],true)&&in_array($list['status'],['approved','in_progress','needs_review'],true);$canAbort=$list['session_status']==='in_progress'&&in_array($list['assignment_status'],['ready','waiting','in_progress','needs_review'],true)&&in_array($list['status'],['draft','approved','in_progress','needs_review'],true);$columnCount=$closeout?8:7;$plannedMoveCount=count(array_filter($moves,static fn($move)=>!empty($move['equipment_id'])));$posted=$error!==''?$_POST:[];$unitLabel=ttOperationsUnitDisplay($list);
?>
<?php include '../includes/header.php';?><title><?=ttHtml($list['switch_list_number'])?> Work Order</title><link rel="stylesheet" href="../assets/css/operations.css"></head><body><?php include '../includes/navbar.php';?><div class="tt-operations-shell"><?php include '../assets/components/sidebar.php';?><section class="tt-ops-page">
<header class="tt-work-order-summary"><div class="tt-work-order-summary-main"><div class="tt-work-order-title"><div><h1><?=ttHtml($list['switch_list_number'])?></h1><p><?=ttHtml($list['title_snapshot'])?></p></div><span class="badge tt-status-<?=ttHtml($list['status'])?>"><?=ttHtml(ttOperationsStatusLabel($list['status'],'switch_list'))?></span></div><ul class="tt-work-order-meta list-unstyled"><li><span>Unit</span><strong><?=ttHtml($unitLabel)?></strong></li><li><span>Crew</span><strong><?=ttHtml($list['crew_name']?:'Unassigned')?></strong></li><li><span>Date</span><strong><?=ttHtml($list['operating_date'])?></strong></li></ul></div><?php $fastClockSessionId=(int)$list['session_id'];include 'fast_clock_widget.php';?></header>
<?php if(!empty($modules['crew_messaging'])&&trim((string)$list['dispatcher_crew_message'])!==''):?><div class="alert alert-warning tt-dispatcher-message"><strong>Dispatcher:</strong> <?=ttHtml($list['dispatcher_crew_message'])?></div><?php endif;?>
<?php if($message):?><div class="alert alert-success"><?=ttHtml($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=ttHtml($error)?></div><?php endif;?>
<?php if($locomotives):?><section class="tt-assigned-locomotives" aria-label="Assigned locomotives"><h2>Assigned Locomotives</h2><div class="tt-locomotive-strip"><?php foreach($locomotives as$locomotive):?><?php $locomotiveLabel=trim($locomotive['reporting_marks'].' '.$locomotive['road_number']);?><div class="tt-locomotive"><?php if($url=ttPhotoUrl($locomotive['photo_filename'])):?><img src="<?=ttHtml($url)?>" alt="<?=ttHtml($locomotiveLabel)?>"><?php else:?><span class="tt-no-photo">No Photo</span><?php endif;?><strong><?=ttHtml($locomotiveLabel)?></strong></div><?php endforeach;?></div></section><?php endif;?>
<form method="post" id="closeoutForm" class="tt-work-order-form" data-planned-moves="<?=$plannedMoveCount?>"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><div class="card mb-3 tt-work-order-moves"><div class="table-responsive tt-mobile-cards"><table class="table tt-work-order-table mb-0"><thead><tr><th>Done</th><th>Photo</th><th>Car</th><th>Action</th><th>Instruction</th><th>From</th><th>Planned To</th><?php if($closeout):?><th>Exceptions</th><?php endif;?></tr></thead><tbody>
<?php foreach($moves as$move):?>
 <?php if($move['action']==='LOCATION'):?><tr class="tt-location-heading"><th colspan="<?=$columnCount?>"><?=ttHtml($move['work_location']?:$move['instruction'])?></th></tr>
 <?php else:?><tr class="tt-move-row"><td class="tt-move-done" data-label="Done"><?php if($move['equipment_id']):?><input class="form-check-input tt-progress-check" type="checkbox" data-move-id="<?=(int)$move['id']?>" aria-label="Mark <?=ttHtml(trim($move['reporting_marks_snapshot'].' '.$move['road_number_snapshot']))?> move complete" <?=$move['progress_complete']?'checked':''?> <?=$closeout&&in_array($list['status'],['approved','in_progress'],true)?'':'disabled'?>><?php endif;?></td><td class="tt-move-photo" data-label="Photo"><?php if($url=ttPhotoUrl($move['photo_filename_snapshot'])):?><button type="button" class="border-0 bg-transparent p-0 tt-photo-button" data-src="<?=ttHtml($url)?>" data-alt="<?=ttHtml(trim($move['reporting_marks_snapshot'].' '.$move['road_number_snapshot']))?>"><img class="tt-car-thumb tt-switch-list-thumb" src="<?=ttHtml($url)?>" alt="<?=ttHtml(trim($move['reporting_marks_snapshot'].' '.$move['road_number_snapshot']))?>"></button><?php elseif($move['equipment_id']):?><span class="tt-no-photo">No Photo</span><?php endif;?></td><td class="tt-move-car" data-label="Car"><strong><?=ttHtml(trim($move['reporting_marks_snapshot'].' '.$move['road_number_snapshot']))?></strong><br><small><?=ttHtml(trim($move['equipment_type_snapshot'].' · '.$move['service_snapshot'],' ·'))?></small></td><td class="tt-move-action" data-label="Action"><strong><?=ttHtml($move['action'])?></strong></td><td class="tt-move-instruction" data-label="Instruction"><?=ttHtml($move['instruction'])?></td><td class="tt-move-from" data-label="From"><?=ttHtml(trim($move['origin_name_snapshot'].' / '.$move['origin_track'],' /'))?></td><td class="tt-move-to" data-label="Planned To"><?=ttHtml(trim($move['destination_name_snapshot'].' / '.$move['destination_track'],' /'))?></td>
 <?php if($closeout):?><?php if($move['equipment_id']):?><?php $moveKey=(string)$move['id'];$postedOutcome=(string)($posted['exception_outcome'][$moveKey]??'');$postedReason=(string)($posted['reason'][$moveKey]??'');$postedDestination=(int)($posted['actual_industry_id'][$moveKey]??$move['destination_industry_id']);$postedTrack=(string)($posted['actual_track'][$moveKey]??$move['destination_track']);$postedNotes=(string)($posted['exception_notes'][$moveKey]??'');?><td class="tt-move-exception-cell" data-label="Move / Exception"><details class="tt-move-exception" <?=$postedOutcome!==''?'open':''?>><summary class="btn btn-sm btn-outline-warning">Add Exception — Move / Not Moved</summary><div class="tt-exception-fields mt-2"><label class="form-label small">Outcome</label><select class="form-select form-select-sm tt-exception-outcome" name="exception_outcome[<?=(int)$move['id']?>]"><option value="" <?=$postedOutcome===''?'selected':''?>>Moved as planned</option><option value="not_moved" <?=$postedOutcome==='not_moved'?'selected':''?>>Not Moved</option><option value="moved_elsewhere" <?=$postedOutcome==='moved_elsewhere'?'selected':''?>>Moved to a Different Location</option></select><div class="tt-not-moved-fields mt-2" <?=$postedOutcome==='not_moved'?'':'hidden'?>> <label class="form-label small">Exception reason</label><select class="form-select form-select-sm" name="reason[<?=(int)$move['id']?>]"><option value="">Choose reason</option><?php foreach($exceptionReasons as$v=>$label):?><option value="<?=$v?>" <?=$postedReason===$v?'selected':''?>><?=$label?></option><?php endforeach;?></select></div><div class="tt-different-location-fields mt-2" <?=$postedOutcome==='moved_elsewhere'?'':'hidden'?>> <label class="form-label small">Actual destination</label><select class="form-select form-select-sm" name="actual_industry_id[<?=(int)$move['id']?>]"><option value="">Choose destination</option><?php foreach($industries as$industry):?><option value="<?=(int)$industry['id']?>" <?=$postedDestination===(int)$industry['id']?'selected':''?>><?=ttHtml($industry['industry_name'])?></option><?php endforeach;?></select><input class="form-control form-control-sm mt-1" name="actual_track[<?=(int)$move['id']?>]" value="<?=ttHtml($postedTrack)?>" placeholder="Actual Track / Spot (optional)"></div><div class="tt-exception-notes mt-2" <?=$postedOutcome===''?'hidden':''?>><label class="form-label small">Exception notes</label><input class="form-control form-control-sm" name="exception_notes[<?=(int)$move['id']?>]" value="<?=ttHtml($postedNotes)?>" placeholder="Explain the exception"></div></div></details></td><?php else:?><td class="tt-move-exception-cell" data-label="Move / Exception"></td><?php endif;?><?php endif;?></tr><?php endif;?>
<?php endforeach;?></tbody></table></div></div><?php if($closeout):?><div class="tt-closeout-controls"><p class="text-muted mb-2">Moves are accepted as planned unless an exception is added.</p><button class="btn btn-success" name="action" value="complete">Complete Work Order</button></div><?php endif;?></form>
<details class="tt-work-order-details"><summary>Details</summary><div class="tt-work-order-details-body"><?php if($list['diagnostic_summary']):?><section class="tt-work-order-diagnostic"><h2>Diagnostic Information</h2><p><?=nl2br(ttHtml($list['diagnostic_summary']))?></p></section><?php endif;?><section class="tt-work-order-revisions"><h2>Revision History</h2><div><?php foreach($revisions as$rev):?><a class="badge text-bg-light" href="work_order.php?id=<?=(int)$rev['id']?>">Rev <?=(int)$rev['revision_number']?> · <?=ttHtml(ttOperationsStatusLabel($rev['status'],'switch_list'))?></a><?php endforeach;?></div></section></div></details>
<div class="tt-ops-actions mt-3"><a class="btn btn-outline-primary" href="print_order.php?id=<?=$id?>" target="_blank">Print / Reprint</a><?php if($canRegenerate):?><form method="post" action="generate.php"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="assignment_id" value="<?=(int)$list['assignment_id']?>"><button class="btn btn-outline-primary">Regenerate Switch List</button></form><?php endif;?><?php if($canApprove):?><form method="post"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><button class="btn btn-success" name="action" value="approve">Approve Revision</button></form><?php endif;?><?php if($canAbort):?><form method="post" onsubmit="return confirm('Abort this assignment? No equipment locations will change.')"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="id" value="<?=$id?>"><input class="form-control d-inline-block w-auto" name="abort_note" placeholder="Abort note"><button class="btn btn-outline-danger" name="action" value="abort">Abort Assignment</button></form><?php endif;?><a class="btn btn-secondary" href="switch_lists.php">All Work Orders</a></div>
</section></div><div class="tt-lightbox" id="photoLightbox" role="dialog" aria-modal="true" aria-label="Car photo"><button type="button" aria-label="Close">×</button><img alt=""></div><script>const token=<?=json_encode(ttOperationsCsrfToken())?>;document.querySelectorAll('.tt-progress-check').forEach(c=>c.addEventListener('change',async()=>{const body=new URLSearchParams({csrf_token:token,move_id:c.dataset.moveId,complete:c.checked?'1':'0'});const r=await fetch('progress.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok){c.checked=!c.checked;alert((await r.json()).error||'Unable to save progress');}}));document.querySelectorAll('.tt-exception-outcome').forEach(select=>{const fields=select.closest('.tt-exception-fields'),sync=()=>{const value=select.value;fields.querySelector('.tt-not-moved-fields').hidden=value!=='not_moved';fields.querySelector('.tt-different-location-fields').hidden=value!=='moved_elsewhere';fields.querySelector('.tt-exception-notes').hidden=value==='';};select.addEventListener('change',sync);sync();});const closeoutForm=document.getElementById('closeoutForm');if(closeoutForm)closeoutForm.addEventListener('submit',event=>{if(event.submitter?.value!=='complete')return;const exceptions=[...closeoutForm.querySelectorAll('.tt-exception-outcome')].filter(select=>select.value!=='').length;const moves=Number(closeoutForm.dataset.plannedMoves||0);if(!confirm(`Complete this work order?\n${moves} planned moves will be applied.\n${exceptions} exception${exceptions===1?'':'s'} will be recorded.`))event.preventDefault();});const box=document.getElementById('photoLightbox'),img=box.querySelector('img'),close=()=>{box.classList.remove('is-open');};document.querySelectorAll('.tt-photo-button').forEach(b=>b.addEventListener('click',()=>{img.src=b.dataset.src;img.alt=b.dataset.alt;box.classList.add('is-open');box.querySelector('button').focus();}));box.querySelector('button').addEventListener('click',close);box.addEventListener('click',e=>{if(e.target===box)close();});document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});</script><?php include '../includes/footer.php';?>
