<?php
require_once dirname(__DIR__).'/generator.php';
require_once dirname(__DIR__).'/prepared_cut_service.php';
function cutExpect($condition,string$message):void{if(!$condition)throw new RuntimeException($message);}
$industries=[
 ['id'=>1,'industry_name'=>'Main 1','industry_type'=>'Staging','ships_services'=>'all','receives_services'=>'all','track_capacity'=>50],
 ['id'=>2,'industry_name'=>'Cargill','industry_type'=>'Industry','ships_services'=>'grain','receives_services'=>'grain','track_capacity'=>8],
 ['id'=>3,'industry_name'=>'Flour Mill','industry_type'=>'Industry','ships_services'=>'grain','receives_services'=>'grain','track_capacity'=>20],
 ['id'=>4,'industry_name'=>'Engine Terminal','industry_type'=>'Yard','ships_services'=>'grain','receives_services'=>'grain','track_capacity'=>50],
 ['id'=>5,'industry_name'=>'Unrelated Warehouse','industry_type'=>'Industry','ships_services'=>'goods','receives_services'=>'goods','track_capacity'=>50],
 ['id'=>6,'industry_name'=>'Local Main 2','industry_type'=>'Main Track','ships_services'=>'all','receives_services'=>'all','track_capacity'=>50],
];
$industryNames=array_column($industries,'industry_name','id');
$car=static fn(int$id,int$location,string$service='grain',string$load='Loaded'):array=>['id'=>$id,'reporting_marks'=>'CUT','road_number'=>(string)$id,'equipment_type'=>'Hopper','operations_service'=>$service,'load_status'=>$load,'current_industry_id'=>$location,'current_track'=>'Main 1','origin_name'=>$industryNames[$location],'photo_filename'=>null];
$startingIds=range(1,15);$cars=[];foreach($startingIds as$id)$cars[]=$car($id,1,$id===15?'coal':'grain');$cars[]=$car(100,4);$cars[]=$car(101,1);$cars[]=$car(102,5,'goods','Empty');foreach(range(200,204)as$id)$cars[]=$car($id,2,'grain','Empty');foreach(range(205,209)as$id)$cars[]=$car($id,3,'grain','Empty');$cars[]=$car(210,6,'grain','Empty');
$baseAssignment=['start_method'=>'prepared_cut','work_scope'=>'entire_railroad','requested_car_count'=>0,'prepared_cut_car_count'=>5,'operating_base_industry_id'=>4,'end_industry_id'=>4,'prepared_cut_industry_id'=>1,'prepared_cut_track'=>'Main 1'];
$entire=ttChooseOperationsMoves($baseAssignment,$cars,$industries,$startingIds,[]);
$entirePulls=array_values(array_filter($entire['moves'],static fn($m)=>$m['action']==='PULL'));$entireSpots=array_values(array_filter($entire['moves'],static fn($m)=>$m['action']==='SPOT'));cutExpect(count($entirePulls)===5&&count($entireSpots)===5,'Five prepared-cut Spots must produce five required empty-car Pulls even when Maximum Additional Pickups is zero.');
$entireIds=array_column($entire['moves'],'equipment_id');cutExpect(!in_array(100,$entireIds,true)&&!in_array(101,$entireIds,true)&&!in_array(102,$entireIds,true)&&!in_array(210,$entireIds,true),'Cars at the base, cut location, unrelated locations, or a support main must not become opportunistic work.');
cutExpect(count($entireIds)===count(array_unique($entireIds)),'Each prepared-cut car may receive at most one movement.');
cutExpect(array_column($entireSpots,'equipment_id')===range(1,5),'Prepared Cut Cars to Switch must cap Spot moves while preserving saved cut order.');
$tenAssignment=$baseAssignment;$tenAssignment['prepared_cut_car_count']=10;$ten=ttChooseOperationsMoves($tenAssignment,$cars,$industries,$startingIds,[]);$tenPulls=array_values(array_filter($ten['moves'],static fn($m)=>$m['action']==='PULL'));$tenSpots=array_values(array_filter($ten['moves'],static fn($m)=>$m['action']==='SPOT'));
cutExpect(count($tenSpots)===10&&array_column($tenSpots,'equipment_id')===range(1,10),'Raising Prepared Cut Cars to Switch to ten must create ten loaded prepared-cut Spots in saved order.');cutExpect(count($tenPulls)===10,'Each of ten loaded Spots must have a required empty Pull that is not limited by Maximum Additional Pickups.');
foreach($tenPulls as$move)cutExpect((int)$move['destination_industry_id']===4,'Required empty Pulls must use the configured terminal or operating base when it has capacity.');
foreach($tenSpots as$move)cutExpect(in_array((int)$move['destination_industry_id'],[2,3],true),'Entire Railroad Spots must use actual customer industries only.');cutExpect(count(array_filter($tenSpots,static fn($m)=>(int)$m['destination_industry_id']===6))===0,'Local Main 2 must never be selected as a customer Spot destination.');
$tenLocations=[];foreach($ten['moves']as$move)$tenLocations[$move['work_location']][]=$move['action'];cutExpect(array_keys($tenLocations)===['Cargill','Flour Mill'],'Exchanges must use deterministic customer ordering.');foreach($tenLocations as$actions){$firstSpot=array_search('SPOT',$actions,true);cutExpect($firstSpot!==false,'Every exchange location must include a Spot.');foreach(array_slice($actions,0,$firstSpot)as$action)cutExpect($action==='PULL','Required empty Pulls must precede Spots.');foreach(array_slice($actions,$firstSpot)as$action)cutExpect($action==='SPOT','No Pull may appear after Spots begin at an exchange location.');}
$pairs=[];foreach($ten['moves']as$move)$pairs[$move['movement_group']][]=$move['action'];foreach($pairs as$actions)cutExpect($actions===['PULL','SPOT'],'Every loaded Spot must remain paired with its required empty Pull.');
$reservedEmptyAssignment=$baseAssignment;$reservedEmptyAssignment['prepared_cut_car_count']=1;$reservedEmpty=ttChooseOperationsMoves($reservedEmptyAssignment,$cars,$industries,$startingIds,[200]);cutExpect(!in_array(200,array_column($reservedEmpty['moves'],'equipment_id'),true)&&count($reservedEmpty['moves'])===2,'A reserved empty must not be used, and no substitute beyond another valid empty at the same customer may be invented.');
$incompatibleAssignment=$baseAssignment;$incompatibleAssignment['prepared_cut_car_count']=15;$incompatible=ttChooseOperationsMoves($incompatibleAssignment,$cars,$industries,$startingIds,[]);
cutExpect(strpos(implode(' ',$incompatible['diagnostics']),'No valid loaded-for-empty customer exchange was available for prepared-cut car CUT 15')!==false,'An unmatched prepared-cut car must receive the named no-exchange diagnostic and remain with the train.');
$byLocation=[];foreach($entireSpots as$move)$byLocation[$move['work_location']][]=$move['equipment_id'];foreach($byLocation as$ids)cutExpect($ids===array_values(array_filter($startingIds,static fn($id)=>in_array($id,$ids,true))),'Prepared-cut order must be preserved within each Spot group.');
cutExpect(count($byLocation)===count(array_unique(array_column($entire['moves'],'work_location'))),'Each Entire Railroad destination must appear once.');
cutExpect(count(array_filter($entire['moves'],static fn($m)=>$m['destination_industry_id']===2))<=8,'Projected destination capacity must be respected.');

$routeStops=[
 ['id'=>1,'industry_id'=>2,'sequence_number'=>1,'exchange_enabled'=>0,'outbound_load_status'=>'Empty','inbound_load_status'=>'Loaded','pull_destination_mode'=>'operating_base','pull_destination_industry_id'=>null,'replacement_source_mode'=>'prepared_cut','replacement_source_industry_id'=>null],
 ['id'=>2,'industry_id'=>3,'sequence_number'=>2,'exchange_enabled'=>0,'outbound_load_status'=>'Empty','inbound_load_status'=>'Loaded','pull_destination_mode'=>'operating_base','pull_destination_industry_id'=>null,'replacement_source_mode'=>'prepared_cut','replacement_source_industry_id'=>null],
];
$routeAssignment=$baseAssignment;$routeAssignment['work_scope']='selected_route';$routeAssignment['requested_car_count']=3;$routeAssignment['prepared_cut_car_count']=10;$route=ttChooseOperationsMoves($routeAssignment,$cars,$industries,$startingIds,[],$routeStops);$routeIds=array_column($route['moves'],'equipment_id');$pulls=array_values(array_filter($route['moves'],static fn($m)=>$m['action']==='PULL'));$spots=array_values(array_filter($route['moves'],static fn($m)=>$m['action']==='SPOT'));
cutExpect(count($pulls)===3,'requested_car_count must limit only additional route pickups.');
cutExpect(count($spots)===10,'Prepared Cut Cars to Switch must cap route Spot work from the prepared cut.');
cutExpect(!in_array(102,$routeIds,true),'Pulls must not originate from an unconfigured route location.');
foreach($spots as$move)cutExpect(in_array($move['destination_industry_id'],[2,3],true),'Selected Route Spots must use industries in the selected Operating Areas only.');
$locations=[];foreach($route['moves']as$move){$locations[$move['work_location']][]=$move['action'];}cutExpect(array_keys($locations)===['Cargill','Flour Mill'],'Route work must follow configured stop order and visit each location once.');foreach($locations as$actions){$firstSpot=array_search('SPOT',$actions,true);if($firstSpot!==false)foreach(array_slice($actions,$firstSpot)as$action)cutExpect($action==='SPOT','Pulls must precede Spots at each route stop.');}
cutExpect(count($routeIds)===count(array_unique($routeIds)),'Prepared-cut and pickup cars must not receive duplicate work.');

$singleEmpty=$car(200,2,'grain','Empty');$correctTrack=ttChooseOperationsMoves($baseAssignment,[$car(1,1),$singleEmpty],$industries,[1],[]);cutExpect(count($correctTrack['moves'])===2,'A prepared-cut car at the saved location and track must remain eligible for a valid exchange.');
$wrongTrackCar=$car(1,1);$wrongTrackCar['current_track']='Track 2';$wrongTrack=ttChooseOperationsMoves($baseAssignment,[$wrongTrackCar,$singleEmpty],$industries,[1],[]);cutExpect(count($wrongTrack['moves'])===0,'A prepared-cut car on another track must not receive a move.');cutExpect(strpos(implode(' ',$wrongTrack['diagnostics']),'Prepared-cut car CUT 1 is no longer on the saved cut track Main 1')!==false,'Wrong-track diagnostics must name the car and authoritative saved track.');
$blankTrackAssignment=$baseAssignment;$blankTrackAssignment['prepared_cut_track']='';$blankTrack=ttChooseOperationsMoves($blankTrackAssignment,[$wrongTrackCar,$singleEmpty],$industries,[1],[]);cutExpect(count($blankTrack['moves'])===2,'A blank saved cut track must use location-only validation.');

cutExpect(ttPreparedCutStatusIsAssigned(['status'=>'assigned']),'An assigned Prepared Cut must be accepted.');foreach(['ready','released','dissolved','in_use','unexpected']as$status)cutExpect(!ttPreparedCutStatusIsAssigned(['status'=>$status]),$status.' Prepared Cuts must be rejected.');cutExpect(!ttPreparedCutStatusIsAssigned(null),'A missing Prepared Cut must be rejected.');
$duplicateStops=[$routeStops[0],array_merge($routeStops[0],['id'=>99,'sequence_number'=>2])];$duplicateRejected=false;try{ttChooseOperationsMoves($routeAssignment,$cars,$industries,$startingIds,[],$duplicateStops);}catch(RuntimeException$e){$duplicateRejected=strpos($e->getMessage(),'Duplicate active industry in the selected Route Areas: Cargill')!==false;}cutExpect($duplicateRejected,'Duplicate Selected Route locations must be rejected by name before any group can be overwritten.');

$same=ttPreparedCutPickupInstruction(['operating_base_industry_id'=>1,'base_name'=>'Main 1'],['current_industry_id'=>1,'industry_name'=>'Main 1','current_track'=>'Track 2','cut_number'=>'CUT-00001','name'=>'Main cut','car_count'=>15]);cutExpect(strpos($same,'Track 2')!==false&&strpos($same,'CUT-00001')!==false,'Same-location pickup instruction must use the saved cut track and identity.');
$travel=ttPreparedCutPickupInstruction(['operating_base_industry_id'=>4,'base_name'=>'Engine Terminal'],['current_industry_id'=>1,'industry_name'=>'Main 1','current_track'=>'Track 2','cut_number'=>'CUT-00001','name'=>'Main cut','car_count'=>15]);cutExpect(strpos($travel,'Run light from Engine Terminal to Main 1 on Track 2')!==false,'Travel pickup instruction must use actual base, cut location, and cut track.');
$generate=file_get_contents(dirname(__DIR__).'/generate.php');$routeEditor=file_get_contents(dirname(__DIR__,2).'/jobs/route.php');$sessionForm=file_get_contents(dirname(__DIR__).'/session_edit.php');$editForm=file_get_contents(dirname(__DIR__).'/assignment_edit.php');$formJs=file_get_contents(dirname(__DIR__,2).'/assets/js/assignment-form.js');cutExpect(strpos($generate,'count($plan[\'moves\'])')!==false,'planned_move_count must count equipment movements only.');cutExpect(strpos($generate,"'instruction-pickup',null")!==false,'Pickup instruction must remain a non-equipment row.');cutExpect(strpos($generate,'$preparedCut[\'current_track\']')!==false,'Pickup row must use the Prepared Cut track.');cutExpect(strpos($generate,'Maximum additional pickups')!==false&&strpos($generate,'Starting train')!==false&&strpos($generate,'Prepared cut cars to switch')!==false,'Generation page must show prepared-cut-specific details.');cutExpect(strpos($sessionForm,'Prepared Cut Cars to Switch')!==false&&strpos($editForm,'Prepared Cut Cars to Switch')!==false&&strpos($sessionForm,'tt-prepared-pickup-help')!==false&&strpos($editForm,'tt-prepared-pickup-help')!==false,'Create/Edit must show separate prepared-cut and additional-pickup limits.');cutExpect(strpos($formJs,"limit.value='0'")!==false&&strpos($formJs,'!form.dataset.assignmentEdit')!==false,'New prepared-cut assignments must default additional pickups to zero without overwriting edits.');cutExpect(substr_count($generate,'ttLoadAssignmentPreparedCut(')>=3&&strpos($generate,"try{\$preparedCut=ttLoadAssignmentPreparedCut")!==false&&strpos($generate,'ttLoadAssignmentPreparedCut($pdo,$assignment,$railroadId,true)')!==false,'GET and locked POST must both enforce Prepared Cut status.');cutExpect(strpos($generate,'ORDER BY position FOR UPDATE')!==false&&strpos($generate,"source_type']??'')!=='prepared_cut'")!==false,'POST must lock and revalidate saved Prepared Cut membership in position order.');cutExpect(strpos($routeEditor,'Operating Area')!==false&&strpos($routeEditor,'operating_areas[]')!==false,'The route editor must use automatically derived, multi-selectable Operating Areas.');cutExpect(strpos($generate,'UPDATE equipment SET')===false,'Generation must not update equipment state.');
$preparedList=file_get_contents(dirname(__DIR__).'/prepared_cuts.php');$preparedEdit=file_get_contents(dirname(__DIR__).'/prepared_cut.php');$preparedService=file_get_contents(dirname(__DIR__).'/prepared_cut_service.php');$sidebar=file_get_contents(dirname(__DIR__,2).'/assets/components/sidebar.php');
cutExpect(ttPreparedCutIsEditable(['status'=>'ready'])&&!ttPreparedCutIsEditable(['status'=>'assigned'])&&!ttPreparedCutIsEditable(['status'=>'in_use'])&&!ttPreparedCutIsEditable(['status'=>'released'])&&!ttPreparedCutIsEditable(['status'=>'dissolved']),'Only Ready Prepared Cuts may be edited.');
$duplicatesRejected=false;try{ttPreparedCutCarIds([12,12]);}catch(RuntimeException$e){$duplicatesRejected=strpos($e->getMessage(),'only appear once')!==false;}cutExpect($duplicatesRejected,'Prepared Cut edits must reject duplicate car IDs.');
cutExpect(ttPreparedCutCarIds([3,1,2])===[3,1,2],'Prepared Cut edits must preserve submitted car order.');
cutExpect(strpos($preparedEdit,'FOR UPDATE')!==false&&strpos($preparedEdit,'ttPreparedCutReplaceCars')!==false&&strpos($preparedEdit,"status='ready'")!==false,'Prepared Cut edits must lock, revalidate, and reject locked lifecycle states.');
cutExpect(strpos($preparedService,'e.railroad_id=?')!==false&&strpos($preparedService,'c.railroad_id=?')!==false&&strpos($preparedService,'current_industry_id=?')!==false,'Prepared Cut membership validation must enforce railroad and location scoping.');
cutExpect(strpos($preparedService,'DELETE pc FROM prepared_cut_cars')!==false&&strpos($preparedService,'INSERT INTO prepared_cut_cars')!==false,'Prepared Cut edits must support removing and adding cars transactionally.');
cutExpect(strpos($preparedEdit,'UPDATE equipment SET')===false&&strpos($preparedService,'UPDATE equipment SET')===false,'Prepared Cut edits must never change physical equipment locations.');
cutExpect(strpos($preparedList,"ttOperationsRequireModule(\$pdo, \$railroadId, 'advanced_roles')")===false&&strpos($preparedEdit,"ttOperationsRequireModule(\$pdo, \$railroadId, 'advanced_roles')")===false,'Prepared Cuts must remain available when Advanced Roles is disabled.');
cutExpect(strpos($sidebar,'showPreparedCuts = $operationsOwner')!==false&&strpos($sidebar,'/operations/prepared_cuts.php')!==false&&strpos($sidebar,"'prepared_cuts'")!==false,'Prepared Cuts must be visible and active for authorized railroad owners.');
echo "prepared_cut_test: OK\n";
